### ISSUE TITLE
odohrelay-crypto-sx failing on dnscrypt-proxy initialization

### ISSUE THREAD

**Issue by tBi2rcAlKQlG** [DNSCrypt/dnscrypt-resolvers#831] opened 2023-09-05 18:14 UTC
I have been using odohrelay-crypto-sx with odoh-cloudfare without issue for many months.  Note that odohrelay-ams is working.  

I am running dnscrypt-proxy 2.1.2 on OpenWrt.

Not sure when this started, but here's what I'm seeing with debug logging:
 
```text
[odoh.cloudflare-dns.com] IP address [162.159.62.1] added to the cache, valid for 12h0m0s

Anonymizing queries for [odoh-cloudflare] via [odohrelay-crypto-sx]

Pausing after ODoH configuration retrieval

[odoh-relay.edgecompute.app] IP address [151.101.129.51] added to the cache, valid for 12h0m0s

POST [https://odoh-relay.edgecompute.app/?targethost=odoh.cloudflare-dns.com&targetpath=%2Fdns-query]: [503 Service Unavailable]
```

**Comment by jedisct1** [comment] 2023-09-05 20:01
Other ODoH servers seem to work fine via `odohrelay-crypto-sx`. Only Cloudflare suddenly started failing.

Has anything changed @chris-wood ?

**Comment by jedisct1** [comment] 2023-09-05 20:43
When running the relay code locally, Cloudflare servers reply as expected.

When running that exact same code on Fastly, a `503` response is returned.

Any idea about what could be happening @chris-wood? Could it be due to rate limits?

**Comment by jedisct1** [comment] 2023-09-05 20:58
@tBi2rcAlKQlG When did Cloudflare stop working for you?

I can see Cloudflare suddenly starting to return a lot 503 errors on June 14. After that date, the number of errors went down, but presumably only because people switched from Cloudflare to other servers, since the overall traffic remained the same. 

<img width="484" alt="Screenshot 2023-09-05 at 22 55 48" src="https://github.com/DNSCrypt/dnscrypt-resolvers/assets/124872/5b5b7c89-61e0-499b-a091-70a846d61203">

**Comment by tBi2rcAlKQlG** [comment] 2023-09-05 21:35
> @tBi2rcAlKQlG When did Cloudflare stop working for you?
> 

I don't have logs going back that far, but that sounds roughly correct.  I recall starting to see the "Trying to fetch the [odoh-cloudflare] configuration again" messages back in June.

**Comment by chris-wood** [comment] 2023-10-05 14:39
Sorry for the late reply here, folks. Is there still an issue here that needs resolving? I haven't tried to reproduce anything myself.

**Comment by jedisct1** [comment] 2023-10-05 16:51
Hi Chris!

Everything looks fine now. I redeployed the service, which maybe changed the pool of IP addresses it is using, and no more 503s.

Thanks!

**Closed by jedisct1** 2023-10-05 16:51 UTC
