### ISSUE TITLE
Signature issues?

### ISSUE THREAD

**Issue by pshirshov** [DNSCrypt/dnscrypt-resolvers#944] opened 2024-08-03 23:04 UTC
It seems like dnscrypt started failing with "invalid signature" after the latest commit.

My config is pretty standard:

```
[sources.'public-resolvers']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']
cache_file = '/usr/share/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
```

**Comment by tutman96** [comment] 2024-08-03 23:18
I am seeing issues related to this as well on my Unifi UCG Ultra, completely breaking "DNS Shield" and taking down DNS completely for my network.

**Comment by themainframe** [comment] 2024-08-03 23:29
I concur. `dnscrypt-proxy` doesn't seem to want to start with this new signature file.

**Comment by mbrumlow** [comment] 2024-08-03 23:30
For those of you using a Unifi UCG you can temporarily get your internet back on line by editing /etc/resolve.conf and placing 1.1.1.1 

At the same time I am seeing this, but also saw the signature errors. 

Aug 03 16:21:12 gateway ubios-udapi-server[63211]: [2024-08-03 16:21:12] [CRITICAL] Unable to retrieve source [public-resolvers]: [Get "https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
Aug 03 16:21:12 gateway ubios-udapi-server[63211]: [2024-08-03 16:21:12] [FATAL] Get "https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md": context dead

Using curl and I have no issue :/

**Comment by tutman96** [comment] 2024-08-03 23:35
Yeah, I was seeing those logs as well. I presume the USG is incorrectly sending all system dns through the proxy and so when it fails, it also fails to download a new list. This is my first time discovering dnscrypt, so pardon the naivety.

**Comment by tutman96** [comment] 2024-08-03 23:37
Here's the logs from dnscrypt-proxy

```
[2024-08-03 19:36:46] [NOTICE] dnscrypt-proxy 2.0.45
[2024-08-03 19:36:46] [INFO] Source [public-resolvers] loading from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md]
[2024-08-03 19:36:46] [INFO] Source [public-resolvers] loading from URL [https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md]
[2024-08-03 19:36:48] [CRITICAL] Unable to retrieve source [public-resolvers]: [Invalid signature]
[2024-08-03 19:36:48] [FATAL] Invalid signature
```

using config 
```
# Generated automatically by ubios-udapi-server
listen_addresses = ['127.0.0.1:5053']
server_names = ['cloudflare','google']
doh_servers = true
[sources]
[sources.'public-resolvers']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
cache_file = '/usr/share/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
```

**Comment by themainframe** [comment] 2024-08-03 23:43
Looks like the signature file (https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md.minisig) might not have been updated in #942 (2b1bddd)? Again just guessing, I'm not familiar with the project.

**Comment by tutman96** [comment] 2024-08-03 23:50
Adding `https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/6ddfdafcb6029cd34961d6fd08c3f95002fc76d7/v3/public-resolvers.md` to the sources list pins it to the previous commit and allows it to continue booting. So agreed that it was a problem with #942.

**Comment by tutman96** [comment] 2024-08-04 00:04
Cross posting https://community.ui.com/questions/DNS-Shield-issue-affecting-multiple-sites-in-different-states-with-different-ISPs/a8513754-e918-4e2c-9bdf-be70b7bd0752 for completeness. They've already linked back to this thread.

**Comment by themainframe** [comment] 2024-08-04 00:07
Looks like it might have just been fixed in f40e753 

Just a question for maintainers... are the signature files not automatically generated as part of the workflow? Seems like it might be very easy to overlook updating them if not!

**Comment by tutman96** [comment] 2024-08-04 00:22
Confirmed working again.

**Comment by pshirshov** [comment] 2024-08-04 00:55
Well, Unifi did a remarkably bad job here. They've had to allow the users to manually override URLs.

But regardless, I would suggest this project to use tags and releases to avoid such situations in the future.

It seems like thousands of various networks were taken down by this.

**Comment by jedisct1** [comment] 2024-08-04 09:01
Signatures are not automatically generated, but I'm working on a way to make sure that they are always valid in the `master` branch. Corrupted files or files with wrong signatures are monitored, but I merged that PR on a Saturday night right before going to bed. Woke up at 2 AM to fix it.

If a signature is invalid, `dnscrypt-proxy` keeps using the previous version of a source file. So that should not cause any disruption.

If this is not the case, make sure you're not using a very old version of the proxy. If you're using a current version, and the previous file isn't used on an invalid signature, there's definitely a bug in `dnscrypt-proxy`.

**Closed** 2024-08-04 09:03 UTC
