### ISSUE TITLE
Possible error in public resolvers list

### ISSUE THREAD

**Issue by theltalpha** [DNSCrypt/dnscrypt-resolvers#310] opened 2020-06-21 13:57 UTC
Hallo!

Since some hours domain names aren't resolving any more on my computer with Debian GNU/Linux. Without going too much into detail, I ran `sudo service dnscrypt-proxy status` and I came across this message:
> [CRITICAL] Unable to use source [public-resolvers]: [Multiple stamps for server [faelix-ch-ipv4] in source from [[https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md]]]

In the current file on GitHub there are indeed two sdns addresses attributed to faelix-ch-ipv4 (and other faelix-ch servers). Might this be the problem why I currently cannot resolve addresses with dnscrypt-proxy?

**Comment by jedisct1** [comment] 2020-06-21 14:05
You are running an old version of dnscrypt-proxy. Upgrade😀

**Comment by theltalpha** [comment] 2020-06-21 16:08
Uh, that was the answer I was not hoping to hear. Well, you know, running a stable Debian version, you are quite restricted when it comes to upgrading to new versions. Actually, the version in Debian stable is 2.0.19. Is there any workaround which I could apply?

**Comment by mpadilla2** [comment] 2020-06-21 16:36
I had this same problem. The workaround I used was to edit the dnscrypt-proxy.toml file and uncomment server_names. Also I needed to comment out [sources.'public-resolvers']. I then needed to uncomment the [static.'google'] entry. I then restarted dnscrypt-proxy and it started resolving using the google entry.

**Comment by dutty5** [comment] 2020-06-21 17:27
> In the current file on GitHub there are indeed two sdns addresses attributed to faelix-ch-ipv4 (and other faelix-ch servers). Might this be the problem why I currently cannot resolve addresses with dnscrypt-proxy?

Hello, I have the same issue. Double entry of identical sdns for faelix servers is really a weird reason of failure, both for dnscrypt-proxy to stop working because of such ridiculous syntax issue and for faelix records' creators. Before talking about upgrade, stop making garbage in your files, or at least teach your program to workaround syntax errors in inputs.

I just wonder how many thousands of servers stopped working?
Very disappointed.

**Comment by Big--Mike** [comment] 2020-06-21 17:55
DNSCloak (iOS app) also broke with this error.
Defining static servers helps, but it's an ugly task in the iOS app. So please consider to fix the list as most users won't notice the source of the problem there.

**Comment by jedisct1** [comment] 2020-06-21 17:58
> Debian stable is 2.0.19

This is very old, and I didn't remember that having multiple stamps was a critical error at that time.

You can't reasonably expect such a version to be tested, even less supported.

One thing that can be done is publish a legacy list, that is a subset of the regular list. Even without multiple stamps, new servers such as Cifra DoH servers are not going to work with versions.

Could anybody running an antique version take on this?

**Comment by jedisct1** [comment] 2020-06-21 18:00
> DNSCloak (iOS app) also broke with this error.

This is more annoying. Entries that cannot be parsed by `dnscrypt-proxy` are simply ignored, but if DNSCloak has its own parser to display the list that doesn't support multiple stamps, we definitely need a legacy version of the list.

**Comment by Big--Mike** [comment] 2020-06-21 18:06
@jedisct1 Actually, I just noticed "dnscrypt-proxy version 2.0.19" is mentioned in [DNCCloak's description](https://apps.apple.com/us/app/dnscloak-secure-dns-client/id1452162351), so maybe the issue is the same...

**Closed** 2020-06-21 20:15 UTC
